ITEM.name = "Base Médicale"
ITEM.uniqueID = "basemedic"
ITEM.category = "Medical"
ITEM.width = 1
ITEM.height = 1
ITEM.uses = 2
ITEM.flag = "m"
ITEM.cure =  "splint"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.price = 0
